# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Visualization Curriculum
author: Jeffrey Heer, Dominik Moritz, Jake VanderPlas, and Brock Craft
logo: idl-logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

launch_buttons:
  colab_url: "https://colab.research.google.com"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/uwdata/visualization-curriculum # Online location of your book
  path_to_book: doc  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
